// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v5.29.2
// source: reactor.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Nothing struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Nothing) Reset() {
	*x = Nothing{}
	mi := &file_reactor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Nothing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Nothing) ProtoMessage() {}

func (x *Nothing) ProtoReflect() protoreflect.Message {
	mi := &file_reactor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Nothing.ProtoReflect.Descriptor instead.
func (*Nothing) Descriptor() ([]byte, []int) {
	return file_reactor_proto_rawDescGZIP(), []int{0}
}

type ReactorStart struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ReactorStart) Reset() {
	*x = ReactorStart{}
	mi := &file_reactor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReactorStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReactorStart) ProtoMessage() {}

func (x *ReactorStart) ProtoReflect() protoreflect.Message {
	mi := &file_reactor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReactorStart.ProtoReflect.Descriptor instead.
func (*ReactorStart) Descriptor() ([]byte, []int) {
	return file_reactor_proto_rawDescGZIP(), []int{1}
}

func (x *ReactorStart) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ReactorActivation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Model   string `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	Id      string `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	Version uint64 `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *ReactorActivation) Reset() {
	*x = ReactorActivation{}
	mi := &file_reactor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReactorActivation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReactorActivation) ProtoMessage() {}

func (x *ReactorActivation) ProtoReflect() protoreflect.Message {
	mi := &file_reactor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReactorActivation.ProtoReflect.Descriptor instead.
func (*ReactorActivation) Descriptor() ([]byte, []int) {
	return file_reactor_proto_rawDescGZIP(), []int{2}
}

func (x *ReactorActivation) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ReactorActivation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ReactorActivation) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type ReactorUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Model   string `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	Id      string `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	Version uint64 `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	Done    bool   `protobuf:"varint,5,opt,name=done,proto3" json:"done,omitempty"`
}

func (x *ReactorUpdate) Reset() {
	*x = ReactorUpdate{}
	mi := &file_reactor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReactorUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReactorUpdate) ProtoMessage() {}

func (x *ReactorUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_reactor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReactorUpdate.ProtoReflect.Descriptor instead.
func (*ReactorUpdate) Descriptor() ([]byte, []int) {
	return file_reactor_proto_rawDescGZIP(), []int{3}
}

func (x *ReactorUpdate) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ReactorUpdate) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ReactorUpdate) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ReactorUpdate) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

var File_reactor_proto protoreflect.FileDescriptor

var file_reactor_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x72, 0x65, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x09, 0x0a, 0x07, 0x4e, 0x6f, 0x74, 0x68, 0x69, 0x6e,
	0x67, 0x22, 0x1e, 0x0a, 0x0c, 0x52, 0x65, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x53, 0x74, 0x61, 0x72,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x22, 0x53, 0x0a, 0x11, 0x52, 0x65, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x41, 0x63, 0x74, 0x69,
	0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07,
	0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x63, 0x0a, 0x0d, 0x52, 0x65, 0x61, 0x63, 0x74, 0x6f,
	0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x18, 0x0a,
	0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07,
	0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x6f, 0x6e, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x64, 0x6f, 0x6e, 0x65, 0x32, 0x89, 0x01, 0x0a, 0x0e,
	0x52, 0x65, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x40,
	0x0a, 0x0b, 0x52, 0x65, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x4c, 0x6f, 0x6f, 0x70, 0x12, 0x13, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x53, 0x74, 0x61,
	0x72, 0x74, 0x1a, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x61, 0x63, 0x74,
	0x6f, 0x72, 0x41, 0x63, 0x74, 0x69, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x00, 0x30, 0x01,
	0x12, 0x35, 0x0a, 0x0b, 0x52, 0x65, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x57, 0x6f, 0x72, 0x6b, 0x12,
	0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x1a, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4e, 0x6f,
	0x74, 0x68, 0x69, 0x6e, 0x67, 0x22, 0x00, 0x42, 0x0d, 0x5a, 0x0b, 0x61, 0x70, 0x6f, 0x67, 0x79,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_reactor_proto_rawDescOnce sync.Once
	file_reactor_proto_rawDescData = file_reactor_proto_rawDesc
)

func file_reactor_proto_rawDescGZIP() []byte {
	file_reactor_proto_rawDescOnce.Do(func() {
		file_reactor_proto_rawDescData = protoimpl.X.CompressGZIP(file_reactor_proto_rawDescData)
	})
	return file_reactor_proto_rawDescData
}

var file_reactor_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_reactor_proto_goTypes = []any{
	(*Nothing)(nil),           // 0: proto.Nothing
	(*ReactorStart)(nil),      // 1: proto.ReactorStart
	(*ReactorActivation)(nil), // 2: proto.ReactorActivation
	(*ReactorUpdate)(nil),     // 3: proto.ReactorUpdate
}
var file_reactor_proto_depIdxs = []int32{
	1, // 0: proto.ReactorService.ReactorLoop:input_type -> proto.ReactorStart
	3, // 1: proto.ReactorService.ReactorWork:input_type -> proto.ReactorUpdate
	2, // 2: proto.ReactorService.ReactorLoop:output_type -> proto.ReactorActivation
	0, // 3: proto.ReactorService.ReactorWork:output_type -> proto.Nothing
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_reactor_proto_init() }
func file_reactor_proto_init() {
	if File_reactor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_reactor_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_reactor_proto_goTypes,
		DependencyIndexes: file_reactor_proto_depIdxs,
		MessageInfos:      file_reactor_proto_msgTypes,
	}.Build()
	File_reactor_proto = out.File
	file_reactor_proto_rawDesc = nil
	file_reactor_proto_goTypes = nil
	file_reactor_proto_depIdxs = nil
}
